// 键盘功能图标的语义类型，按钮仍保留中文辅助功能名称。
package io.github.utyoinog.yagamiime;

enum KeyIcon {
    KEYBOARD, CLIPBOARD, EDIT, SELECT, HIDE, EXPAND, COLLAPSE, DELETE, ENTER,
    SHIFT, CAPS_LOCK, PASSWORD, AUTHENTICATOR, MORE, GLOBE, SETTINGS, COPY, CUT, PASTE, LEFT, RIGHT, HOME, END, BACK, SYMBOLS, TRASH, PIN
}
